/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteRouteImport } from './routes/admin/loginRoute'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardSearchClientRouteImport } from './routes/admin/dashboard/search-client'
import { Route as AdminDashboardRegisterClientRouteImport } from './routes/admin/dashboard/register-client'
import { Route as AdminDashboardSeeAllClientTableRouteImport } from './routes/admin/dashboard/SeeAllClientTable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRouteRoute = AdminLoginRouteRouteImport.update({
  id: '/admin/loginRoute',
  path: '/admin/loginRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSearchClientRoute =
  AdminDashboardSearchClientRouteImport.update({
    id: '/search-client',
    path: '/search-client',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardRegisterClientRoute =
  AdminDashboardRegisterClientRouteImport.update({
    id: '/register-client',
    path: '/register-client',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardSeeAllClientTableRoute =
  AdminDashboardSeeAllClientTableRouteImport.update({
    id: '/SeeAllClientTable',
    path: '/SeeAllClientTable',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/loginRoute': typeof AdminLoginRouteRoute
  '/admin/dashboard/SeeAllClientTable': typeof AdminDashboardSeeAllClientTableRoute
  '/admin/dashboard/register-client': typeof AdminDashboardRegisterClientRoute
  '/admin/dashboard/search-client': typeof AdminDashboardSearchClientRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/loginRoute': typeof AdminLoginRouteRoute
  '/admin/dashboard/SeeAllClientTable': typeof AdminDashboardSeeAllClientTableRoute
  '/admin/dashboard/register-client': typeof AdminDashboardRegisterClientRoute
  '/admin/dashboard/search-client': typeof AdminDashboardSearchClientRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/loginRoute': typeof AdminLoginRouteRoute
  '/admin/dashboard/SeeAllClientTable': typeof AdminDashboardSeeAllClientTableRoute
  '/admin/dashboard/register-client': typeof AdminDashboardRegisterClientRoute
  '/admin/dashboard/search-client': typeof AdminDashboardSearchClientRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/loginRoute'
    | '/admin/dashboard/SeeAllClientTable'
    | '/admin/dashboard/register-client'
    | '/admin/dashboard/search-client'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/loginRoute'
    | '/admin/dashboard/SeeAllClientTable'
    | '/admin/dashboard/register-client'
    | '/admin/dashboard/search-client'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/loginRoute'
    | '/admin/dashboard/SeeAllClientTable'
    | '/admin/dashboard/register-client'
    | '/admin/dashboard/search-client'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminLoginRouteRoute: typeof AdminLoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loginRoute': {
      id: '/admin/loginRoute'
      path: '/admin/loginRoute'
      fullPath: '/admin/loginRoute'
      preLoaderRoute: typeof AdminLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/search-client': {
      id: '/admin/dashboard/search-client'
      path: '/search-client'
      fullPath: '/admin/dashboard/search-client'
      preLoaderRoute: typeof AdminDashboardSearchClientRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/register-client': {
      id: '/admin/dashboard/register-client'
      path: '/register-client'
      fullPath: '/admin/dashboard/register-client'
      preLoaderRoute: typeof AdminDashboardRegisterClientRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/SeeAllClientTable': {
      id: '/admin/dashboard/SeeAllClientTable'
      path: '/SeeAllClientTable'
      fullPath: '/admin/dashboard/SeeAllClientTable'
      preLoaderRoute: typeof AdminDashboardSeeAllClientTableRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardSeeAllClientTableRoute: typeof AdminDashboardSeeAllClientTableRoute
  AdminDashboardRegisterClientRoute: typeof AdminDashboardRegisterClientRoute
  AdminDashboardSearchClientRoute: typeof AdminDashboardSearchClientRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardSeeAllClientTableRoute: AdminDashboardSeeAllClientTableRoute,
  AdminDashboardRegisterClientRoute: AdminDashboardRegisterClientRoute,
  AdminDashboardSearchClientRoute: AdminDashboardSearchClientRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminLoginRouteRoute: AdminLoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
